### ISSUE TITLE
Chapter 2, page 15-18 Instances and properties

### ISSUE THREAD

**Issue by sgillesp-ai** [KGConf/Bookclub-DemystifyingOWL#10]
In Table 2.1 (p 15) Classes and subClasses have predicates that define how Classes relate to subClasses, and how subClasses relate to _Individuals. Even though these they express important relationships, they are not considered object properties, right? On page 18 it says an "object property: relates an individual to another individual." If they aren't object properties what kind of predicates are they? Metadata? 
 
If OWL object properties are confined only to instances, how do you express relationships between more abstract classes that you know exist and want to explore?

If this example below helps, good. If not, that's ok, too. 

To sketch this out as a simple [but imprecise] example: schools need computers. 
•	Education relates to Technology (schools need computers)
•	Technology and Economics (computers cost money)
•	Education relates to Economics (schools need money)
•	Economics relates to Politics (Money [may be] provided by legislatures) 
•	Politics relates to Law (legislatures pass budget bills [for schools])

**Comment by uscholdm** [comment]
Excellent observation and good question. 

> If OWL object properties are confined only to instances, how do you express relationships between more abstract classes that you know exist and want to explore?

**Short Answer**: You use OWL constructs such as `rdfs:subClassOf` and `rdfs:subPropertyOf` which we will get into in gloroius detail in part 2 of the book. 

**Longer answer**: You were on the right track when you said: "Metadata?".  The ontology can be thought of as the metadata (classes and properties). The data links instances to other instances or to literals.  The ontology is defined _using_ constructs from OWL, such as `rdfs:subClassOf` and `rdfs:subPropertyOf`. 

The properties that are part of the OWL language itself are the only ones that you can use to link classes to classes (e.g. `rdfs:subClassOf` or classes to properties (when creating restrictions).   For example, in the ontology (metadata) you can have a restriction that says every instance of the class `Legistature` is connected to an instance of `Bill` via the `passesLegislation` property.

.

**Comment by sgillesp-ai** [comment]
I will stay tuned to Part 2. Thanks for your courteous answers.
