### ISSUE TITLE
Chapter 2 IRIs (Table 2.4 Page 21)

### ISSUE THREAD

**Issue by sgillesp-ai** [KGConf/Bookclub-DemystifyingOWL#12]
I understand the need for Internationalized Resource Identifiers (IRI) and that they stand for actual web addresses. But when you have a program that depends on so many different IRIs, what happens if the links break? I imagine you may borrow from other ontologies that have their own IRIs. Do you get 404 error? Does your ontology break?

**Comment by uscholdm** [comment]
You touch on an important issue. Ideally, **all** IRIs should be de-referenceable.  We do not live in an ideal world.  In enterprise applications it is more of a nicety than a necessity to dereference IRIs. IRIs are used in triples which are loaded into a triple store and referred to in queries. 

The need to put the IRI to an open web server generally does not arise in the enterprise KG applications that we develop.  If this is a requirement, then you need to do extra work. Note: you have not control over this for IRIs in other people's namespaces. You can only control this in your own namespaces where you control the domain name.
