### ISSUE TITLE
Chapter 2 Nomenclature

### ISSUE THREAD

**Issue by Robert-Muil** [KGConf/Bookclub-DemystifyingOWL#13]
1. If an Ontology can have individuals, what is the difference between that and a Knowledge Graph?
2. axiom vs. statement vs. assertion vs. triple ?

**Comment by uscholdm** [comment]
The term 'knowledge graph' is a bit ambiguous. A KG necessarily consists of triples. There are wo main kinds of triples: data and metadata. The ontology is made up of the metadata triples.  

Here are three different ways to have a set of triples:
1. You just have an ontology and no data
2. You just have data, and no ontology.
3.  You have both the ontology and the data

The term, 'knowledge graph', has been used to refer to any or all of these. I tend to use it for the third case.


5. If all you have is the ontology, some people might choose to call that a knowledge graph. Some prefer to think of the knowledge graph as the ontology plus the data. Others are happy to just call the data a knowledge graph, where there are no definitions for the properties and there are no classes at all. This is commonly called 'linked data'.
The triples may be the data, or they may be part of the ontology.

**Comment by uscholdm** [comment]
> axiom vs. statement vs. assertion vs. triple ?

There is a lot of overlap in these terms. What binds them all is that they each 'say that something is so'. 
- if the context is logic, the term 'axiom' is commonly used
- if the context is broad, English or anything, the terms 'statement' and 'assertion' are commonly used
- if the context is linked data and RDF, the term 'triple' is used.
