### ISSUE TITLE
Chapter 2 - chat session

### ISSUE THREAD

**Issue by marielmat** [KGConf/Bookclub-DemystifyingOWL#16]
11:06:22 From  Bob Lucas  to  Everyone : How do we get the e6Tools
11:07:02 From  msesboue  to  Everyone : I Don't think it is an opensource one Bob
11:30:48 From  Julieta Sanchez  to  Everyone : What is the benefit of having a subclass relationship vs equivalence statement?
11:31:15 From  Dean Allemang  to  Everyone : no problem; Julieta's question is a key one, and leads into the comment I was going to make
11:31:25 From  Ellie Young  to  Everyone : Perfect!
11:32:58 From  Julieta Sanchez  to  Everyone : yes, thank you!
11:33:01 From  Robert Muil  to  Everyone : My understanding is that the equivalence statement means that not only are these class memberships necessary, they are also *sufficient*
11:40:28 From  Robert Muil  to  Everyone : A follow-on- is the (N) not redundant?
11:45:14 From  Keith Corbett  to  Everyone : Is TopBraid Composer a good visual tool for modeling OWL?
11:45:29 From  matei  to  Everyone : this one https://www.elgrapho.com/ ?
11:46:02 From  msesboue  to  Everyone : grapho is the one used by data.world
11:46:13 From  Ellie Young  to  Everyone : gra.fo
11:46:20 From  Veronika Heimsbakk  to  Everyone : TopBraid EDG has become a splendid SHACL editor tho. :)
11:46:28 From  matei  to  Everyone : thank you ellie!
11:46:30 From  Ellie Young  to  Everyone : https://gra.fo/
11:46:59 From  Dean Allemang  to  Everyone : @Veronica yes - TopQuadrant really put their weight behind SHACL
11:54:39 From  Dean Allemang  to  Everyone : When I lived in Switzerland, I was talking to my colleagues at lunch (in French) about this practice in German.  A German speaker at the table said, "in practice, we don't really do this very often".  I replied "Luftseilbahnfuhrerscheinprufungsanstalt" (the office that administers the issuance of driving licenses for aerial cable cars).   The French speakers scored one that day.
12:01:24 From  Robert Muil  to  Everyone : I have to drop for a call. Thank you for the session!
12:01:30 From  Ellie Young  to  Everyone : Thanks Robert!
12:03:33 From  Keith Corbett  to  Everyone : An exception is an IRI used in an import statement - tools like Protege will attempt to download the ontology file
12:04:08 From  Steve Gillespie  to  Everyone : Can you define dereference?
12:04:48 From  Keith Corbett  to  Everyone : Dereference == Use the protocol as defined in the IRI to make an api "call" to download the resource

**Comment by uscholdm** [comment]
If someone wishes to pull form this a specific question, I am happy to answer it.
