### ISSUE TITLE
Chapter 2 Errata

### ISSUE THREAD

**Issue by dhurlburtusa** [KGConf/Bookclub-DemystifyingOWL#17]
- Pg 20, last paragraph, first sentence: Shema => Schema.
- Pg 24, second paragraph, second sentence: `...Figures 1.1, 1.2, and 1.4 in and re-draw...` => `...Figures 1.1, 1.2, and 1.4 and re-draw...`. (I don't think the `in` is necessary.)
- Pg 25, last paragraph, last sentence: `Figure 2.6...` => `Figure 2.5...`.
- Pg 28, first bullet list, second bullet point: `...to indicate that a one class...` => `...to indicate that one class...` (drops the extra article).
- Pg 29, second to last paragraph, last sentence: `...be used help...` => `...be used to help...` (missing preposition).
- Pg 30, first paragraph, last sentence: `We purposely we created...` => `We purposely created...` (drops the extra pronoun).
- Pg32, second paragraph, second sentence: `...construct, subClassOf is used...` => `...construct, subClassOf used...` (drops the extra verb).
- Pg32, second paragraph, second to last sentence: `...because it not intuitive.` => `...because it is not intuitive.` (add missing verb).
- Pg 35, first list, second bullet point: `Ithas...` => `It has...` (add missing space).
- Pg 36, paragraph starting with "As previously...", fourth sentence, `...these newfangled...` => `...these new fangled...` (add missing space).
- Pg 37, first IF/THEN section: `(2) that is a...` => `(2) it is a...`. (Other ways to fix exist.)
- Pg 42, paragraph starting with "We have already...", third sentence: `...a subclass person, ...` =>`...a subclass of person, ...` (add missing preposition).
- Pg 44, first paragraph, missing Oxford (aka Harvard) comma in list of items. If you don't care about this level of knit pick, then I won't point out anymore regarding the Oxford comma.
- Pg 45, handled in another GH issue.
- Pg 47, handled in another GH issue.
- Pg 48, first paragraph, third sentence: `...can give it name to if...` => `...can give it a name too if...` (add missing article and fix typo).
- Pg 48, second paragraph, fourth paragraph: `...means that every Person is also a ...` => `...means that every Patient is also a ...` (I believe Person is suppose to be Patient).
- Pg 49, first bullet list: inconsistent punctuation endings (some with periods and some not).
- Pg 50, first paragraph: `...given class have One important...` =>`...given class have. One important...` (missing punctuation).

If any of these are too knit picky to care about, please let me know and I will not post that class of errata.

BTW, good book so far.

**Comment by jtyzzer** [comment]
Pg 48, in "...using set intersection and compliment," "compliment" should be "compl**e**ment."
Pg 49, "...must be a member **or**," should read "must be a member **of**."

**Comment by uscholdm** [comment]
Holy smoly! Have you ever considered being a professional editor?  It is useful to keep posting these. I will collect them up and send to the publisher for an updated version.

**Comment by dhurlburtusa** [comment]
I even left out some where I noticed there were multiple spaces (I only knew that because it was in a bullet list all starting with the same set of words but was didn't align like the other.) I also left out missing Oxford commas because some people don't care about. I personally prefer the Oxford comma because it minimizes ambiguity.
