### ISSUE TITLE
Chapter 3, Section 3.1.5 Literals and Datatypes (Figure 3.5). Section 3.1.6 Metaclass

### ISSUE THREAD

**Issue by sgillesp-ai** [KGConf/Bookclub-DemystifyingOWL#19]
In the owl:Class oval (Figure 3.5, upper left) it looks like there is hierarchy. For example, Doctor and Nurse are a kind of HealthCareProvider; a Corporation is a kind of Legal Entity. Is this an optical illusion? In owl:Class are all the members just free-floating individuals, unrelated instances? Does the hierarchy come when they become subclasses of owl:Thing (Figure 3.6, lower left)?

What is the benefit of modeling what-is-in-a-set using a combined approach, like using owl:Class (no ovals allowed) and owl:Thing (ovals welcome)? At the end of 3.1.6, you suggest that is something for which we should stay tuned to Chapter 7 for. Maybe it will be clearer (to me) when we get there.  

Sorry for the bad timing.

**Comment by uscholdm** [comment]
> In the `owl:Class` oval (Figure 3.5, upper left) it looks like there is hierarchy.

There is no diagrammatic connection between Doctor and Person. The reason it looks like a hierarchy is probably the fact that you know the meaning of the terms.  If they were in Greek, it would look more like a set of 'free-floating individuals, unrelated instances." as you put it.   So yeah, I think it is a lot like an optical illusion. Your brain added a link that was not there.

> In owl:Class are all the members just free-floating individuals, unrelated instances?

Yes, to repeat for emphasis.

> Does the hierarchy come when they become subclasses of owl:Thing (Figure 3.6, lower left)?

Exactly so! ( but you mean fig 3.5)

**Comment by uscholdm** [comment]
> What is the benefit of modeling what-is-in-a-set using a combined approach, like using owl:Class (no ovals allowed) and owl:Thing (ovals welcome)?

The ovals being allowed or not is really just an artifact of the diagram.  In the triples, there is no problem with an IRI being a member of a class, but also being a class with members. Note that this is only allowed for classes that are part of the OWL language. You cannot create your own metaclasses - as will be explained in chapter 7, with examples.

The advantage of modeling this way is so it can all be represented as triples in a consistent way.  Although it is tricky to get your head around this idea, it does conform to common sense.  A class corresponds to a set of individuals. The class might be `doe:Person`, and the individuals are particular human beings. The class, `owl:Class` has members that are not in the subject area you are modeling, but in the model itself.  One member of the set that corresponds to the class, `owl:Class` is `doe:Person`.  This way there is just one property for saying something is a member of a class (`rdf:type`).

**Comment by uscholdm** [comment]
BTW, thank you for asking this question.  Many will have a hard time with this material.  They can all benefit from this extra discusion.
