### ISSUE TITLE
Ch. 4 - Selective inference for property with many domain classes/ranges 

### ISSUE THREAD

**Issue by julietasanper** [KGConf/Bookclub-DemystifyingOWL#28]
If you have a predicate that applies to many classes but you only want the reasoner to infer knowledge about a specific class, is that possible? Selective inference? Adding it to the reasoner level would mean that we would need to hardcode the domain/ranges of predicates we want to infer? Or is there a dynamic way of doing this?

**Comment by julietasanper** [comment]
Per @msesboue 

I think it would be possible, but would not be expressed within the ontology itself. It would be at the reasonner level that it would be specified as a rule. With some triple stores you can also decide to infer triples only when you ask the question (SPARQL query). Those triples are only used for the query and lost afterwards.

(Note that it is only a guess from what I have seen, this information is not verified)
You would define the domain and range as it should be in the ontology. But then when infering triples you can ask the reasoner to focus only on infered triples related to a specific class

**Comment by uscholdm** [comment]
Lets take an example property: `partOf`. It can be used to connect all sorts of things:
- steering wheels to cars
- keyboards to laptops
- branches to trees

I'm not sure what you want, so I'm going to guess.  I think you are asking whether you can decide to have inference only work for say parts of cars, but not parts of laptops or trees.  Lets consider two cases. 
1. OWL inference
2. SPARQL inference 

You cannot stop OWL inference in this way a single `partOf`.  You could create a separate property for being a part of a car and give it domain and range which would trigger inference for just that property.   

You can do whatever you want in SPARQL.  Specifically, you can decide exactly what to infer under what circumstances.
I hope that helps.
