### ISSUE TITLE
Explain "grounding triples" pg 132 (Bob Lucas)

### ISSUE THREAD

**Issue by ghost** [KGConf/Bookclub-DemystifyingOWL#29]
Last sentence before Section 5.4.3 pg 132 
"The thicker lines are the **_grounding triples_** for the respective restrictions"

**Comment by uscholdm** [comment]
I first introduce this term at the beginning of section 5.4.2. I say: "A restriction denotes a set of subjects of triples using a given predicate that satisfy certain conditions. I think of these [_triples that the subjects are taken from_] as the restriction’s **grounding triples**. They are depicted in thick [black] lines in Figure 5.7"   THose triples are the basis or foundation for what the restrictionis, hence the term 'grounding triples'. Here is that figure marked up:

![image](https://user-images.githubusercontent.com/10777545/109603077-2e1a5600-7ad6-11eb-9350-9429533df310.png)
