### ISSUE TITLE
Creating attributes for things that are not events.

### ISSUE THREAD

**Issue by uscholdm** [KGConf/Bookclub-DemystifyingOWL#3]
Submitted by M. 

Is there a way to create attributes for a relation/predicate other than creating an event (like "John Doe's visit")?

**Comment by uscholdm** [comment]
Yes, anything can have attributes.  Here are various examples:
- A person has a name, and a date of birth
- An corporation may have an official name 
- A city has a date of incorporation, a name and maybe a nick name like "The Big Apple"

You can say that a person works for a corporation that is located in a city - all without bringing events into the picture. 

In chapter 2,  we describe how to model attributes in OWL.

**Comment by ChuckNoelke** [comment]
Thanks for your answers!
But how to create an attribute for visiting a doctor at a certain time? It is not possible to connect the time stamp to "visiting" as this is a predicate.
It seems that for modeling processes there is no other way than using an event scheme.
All the best, Marcus

**Comment by uscholdm** [comment]
If you want to visit a Doctor at a certain time, the visit is in fact an event. Why do you want to avoid modeling it that way? 

In an emerging standard called RDF*, one can put certain information on the link itself.  Is that what you want?  The material in section 7.3 is somewhat related - that that's many chapters later. 

> It seems that for modeling processes there is no other way than using an event scheme.

 Processes are a different matter - they are quite interesting but not very straight-forward. They could take up a whole chapter!   There are always  number of options - the right choice depends on what you want from the model.   Bring up this question later on after we cover more material. Chapter 6 would be a good fit.

**Comment by ChuckNoelke** [comment]
Ok. Great. Thanks! Let's keep these topics for further chapters.
