### ISSUE TITLE
Chapter 5/6 - On Restrictions

### ISSUE THREAD

**Issue by ChuckNoelke** [KGConf/Bookclub-DemystifyingOWL#32]
Is there a Sparql-query to find matched or unmatched restrictions? 
E.g. I insert an instance of a class Module ("module_1"). For the class Module I have defined several restrictions of type qualified cardinality exactly 1 with related objects (module name, module serial number, module function code, etc). For the instance "module_1" only the module name is asserted, but there are no items for module serial number or module function code. The inference engine will not complain becuase if the Open World Assumption. So, is it possible to write a query to check what data is missing and what data is already available?

**Comment by uscholdm** [comment]
Yes. You could do this using SHACL (whose precise meaning is expressed in terms of SPARQL) or you can do it in SPARQL directly. SHACL provided syntax to do this very conveniently. Its a bit of effort in SPARQL, but not too bad.   To ensure that every instance of the class Module has exactly one serial number, you write a query to find every example that breaks the rule and report back about them. Then go fix the data and run the query again until the data errors are gone.   

There are two ways that the problem could arise. There might be no serial number at all, or there might be two different ones.  You find offending examples for both cases and union them together.  It would work something like this:

```
SELECT ?badModule where
 {
    ?badModule a :Module .
    {FILTER NOT EXISTS ?badModule :hasSerialNumber ?sn}
    UNION
    {?badModule :hasSerialNumber ?sn1 , ?sn2 .
     FILTER (?sn1 != ?sn2) } 
  }
```

NOTE: I did not test this, so it could easily need to be tweaked to get it working.
