### ISSUE TITLE
datatype xsd:string vs xsd:string with a language specified

### ISSUE THREAD

**Issue by msesboue** [KGConf/Bookclub-DemystifyingOWL#33]
(Protege related question)

Is there a difference in meaning between the datatype xsd:string and xsd:string with a language specified?

I tried defining a range xsd:string for a data property "title". Then I defined some individuals which I link to a string using this data property "title" AND I specify a language. But then when I run the reasoner (Pellet I think) it tells me this is inconsistent. And if I remove the language it is not inconsistent anymore.

**Comment by msesboue** [comment]
From Danny:
I assume the reason is because a string with a language such as "hello"@en doesn't have the datatype of xsd:string but it has a datatype of rdf;langString.
I mean rdf:langString.
Probably need to say the range can be either an xsd:string or an rdf:langString.

**Comment by msesboue** [comment]
From Dean:
That's right; and rdf:string and rdf:langString are disjoint; hence you have something that is a member of two disjoint classes (which is a contradiction)

**Comment by uscholdm** [comment]
The original question was: 

> Is there a difference in meaning between the datatype xsd:string and xsd:string with a language specified?

In terms of the real world meaning, there is no difference. One is giving a bit more information, that's all.  In terms of the formal semantics of OWL & RDF, there is a difference, as Dean points out. Specifically, `rdf:string` and `rdf:langString` are disjoint
