### ISSUE TITLE
Chapter 7, Section 7.3 N-ary Relationships, Figure 7.7 (p 172), Steve Gillespie

### ISSUE THREAD

**Issue by sgillesp-ai** [KGConf/Bookclub-DemystifyingOWL#34]
Need your help, please. Could you explain the arrows in the lower portion of Figure 7.7 which illustrate, “Michael Uschold was employed at Boeing from 1997-2008.” 

Both arrows going from :Employment (going to both :Organization and Person) are identical; they use the property **:employmentBy**. 

But, it seems like the arrows describe a different relationship. Wouldn’t the relationship going from :Employment to the :Organization (**:_Boeing**) be different than the relationship going from :Employment to the Person (**:_MichaelUschold**)? 

Maybe the property arrow going from :Employment (**:_MU_EmployedByBoeing**) to the :Organization should be **:employedBy**? This was the period MU was _employed by_ Boeing. This was the period of _employment by_ Michael Uschold.

Sorry if this is in the weeds and sorry it's late.

**Comment by uscholdm** [comment]
Thank you for finding a bug in Figure 7.7 (p172). The arrow from the `Employment` instance to the `Person` instance (me) should have been called `employmentOf`. This was a copy-and-paste-and-forget-to-edit error.
