### ISSUE TITLE
PREFACE - Role of Inferencing

### ISSUE THREAD

**Issue by dallemang** [KGConf/Bookclub-DemystifyingOWL#4]
In the preface, you outline three issues that OWL responds to in information technology.  Those are modularity of data models, global identifiers in data schemas and representing meaning.   These are excellent motivations for a new language.

What is the role of inferencing in satisfying any of these needs?

**Comment by uscholdm** [comment]
Inferencing and meaning go hand in hand.   Logic allows you to specify a lot about what things mean. Inference generated new information based on that meaning. Inference also can detect logical inconsistencies.

I don't see much of a connection between inference and global identifiers or modularity, per se.   

The bigger point is that even now, many years after OWL came out, the role of OWL inference is mainly for validation of the ontology.  We are using it more and more as triple stores do a better job of it.
