### ISSUE TITLE
Is the individual/class distinction the most fundamental way to cleave the universe into its parts?

### ISSUE THREAD

**Issue by Robert-Muil** [KGConf/Bookclub-DemystifyingOWL#5]
This is rather philosophical, but it seems to me that all ontology frameworks impose a most fundamental distinction between Individuals and Classes - that is between _entities_ and _kinds of entities_ - and this is more fundamental than a split between, for example, physical and abstract.

My question is whether there are alternatives? Is there another way of carving the universe at its most fundamental?

**Comment by uscholdm** [comment]
That's an interesting question - one that philosophers have been grappling with for a long time. The issue arises in the design of upper ontologies, which often encode these major distinctions about the world, such as physical vs. abstract.  Another favorite top-level distinctions is between things that happen  in time (an event) vs. things that exist over time (a physical object).  The terms: 'endurant' and 'perdurant' are used by philosophers and in some upper ontologies to refer to this.  The endurant/perdurant or physical/abstract distinctions are about the world per se.  The class vs. individual distinction feels different to me, though I cannot find just the right words to say how.  It feels more meta, more about the representation of the world than about the world itself.

The truth is there are many ways to slice and dice the world and to represent it in an ontology.   There is no one right way that everyone will agree to.

**Comment by Robert-Muil** [comment]
Yes the individual/class distinction is definitely different, and your statement that it is not about the world but about its representation feels intuitive to me: except that if I am representing the world, that representation is also in the world!

I realise these are primarily academic pontifications, but I was interested in whether, practically, any other approaches have been made: any way to start a representation of the world other than this individual/class dichotomy?

**Comment by uscholdm** [comment]
> your statement that it is not about the world but about its representation feels intuitive to me: except that if I am representing the world, that representation is also in the world!

That is true, but its one 'level' up.

**Comment by uscholdm** [comment]
> I was interested in whether, practically, any other approaches have been made: any way to start a representation of the world other than this individual/class dichotomy?

Smalltalk took the view that there was no difference between an individual and a class.  I'm not aware of anything in the knowledge representation / ontology world.

**Comment by Robert-Muil** [comment]
Cool, Smalltalk is then an example of what I was interested in. Do you consider it to be so because classes are first-class objects, and are thus in some sense individuals also? In that sense Python is also a good example, because classes are first-class objects, can be manipulated exactly like instances of them. There remains a difference, however, that instances cannot themselves be instantiated...

**Comment by uscholdm** [comment]
Removing the class/individual distinction never aligned with my common sense. We have reached the limit of my knowledge in this area.

**Comment by Robert-Muil** [comment]
A wonderfully worded punctuation to the discussion!
