### ISSUE TITLE
Chapter 2 - pg 32 - fig 2.7 - 

### ISSUE THREAD

**Issue by ChuckNoelke** [KGConf/Bookclub-DemystifyingOWL#7]
Why is in case of "subClassOf" no "AND" operator necessary? Fig 2.9 shows "equivalent to" with AND operator.

**Comment by uscholdm** [comment]
In figure 2.9 there is an explicit equivalentClass axiom which is not the case in figure 2.7. There are instead, three subClassOf axioms.

The choice of showing the "AND" in the diagram when there is an equivalentClass axiom is a notational convention of the e6 tool.
