### ISSUE TITLE
Chapter 2 - e6 Visio Plugin

### ISSUE THREAD

**Issue by ChuckNoelke** [KGConf/Bookclub-DemystifyingOWL#8]
Is the Visio Plugin commercially available? Could you recommend other tools? Anybody has experience with Ontodia?

**Comment by uscholdm** [comment]
The Visio plugin is not commercially available.  We used in in house at Semantic Arts for many years, but abandoned it when we moved to collaborative ontology development.   I am not aware of any good OWL authoring tools thare are primarly visual/graphical in nature. Many have tried. The e6Tools is the best notation I have seen. All others are very non-intuitive and thus hard to work with -OR- they are too simple, missing out on key OWL constructs.

I am not aware of Ontodia.
